spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.ysgnvfnewnofqeslutqj
    password: ubuntu
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000       # 30 seconds
      max-lifetime: 60000       # 60 seconds
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080
