spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.ysgnvfnewnofqeslutqj
    password: 2RCeqWgmC82HltdM
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      idle-timeout: 20000
      max-lifetime: 10000
      connection-timeout: 30000



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080
